- include/config.h
- include/util.h
- src/usbd_desc.c
- src/util.c
Instead of hardcoding the serial number in the firmware, use the
device's manufacturer-provided UID as the serial number.
This makes it easier to distinguish between multiple adaptors plugged
into the same host without having to build a separate firmware for each
one.
> Use chip UID as USB serial number

- src/util.c
The logic for enable_irq is backwards; it should enable interrupts when primask is 0, not 1.
> Fix enable_irq interpretation of primask

- .travis.yml
- README.md
This would add continuous integration and deploys if a version is tagged.
Every target will be available as its own tarball in the releases section.
The repo owner would need to change the section:
```
api_key:
secure: <encrypted token>
```
> Adds Travis-Ci and deploy on tags

- README.md
This adds the Copperforge VulCAN (https://shop.copperforge.cc/products/ac41) to the supported device list in the README.
> Add Copperforge VulCAN

- include/util.h
- src/main.c
- src/usbd_gs_can.c
- src/util.c
Avoid using <assert.h> because the standard assert() pulls in
fprintf and its dependencies, as well as including ` __FILE__:__LINE__`
strings for each assert() call. All this has an unacceptable memory
cost, as well as being useless since there is nowhere to printf *to*.
Currently assert_basic() was added to check calloc() return values;
in case of failure we simply halt the core with BKPT(0). This could be
improved and refined.
@brian-brt , @normaldotcom , thoughts / comments ?
> Add basic assert checks

- CMakeLists.txt
- cmake/gitversion.cmake
- include/config.h
- src/usbd_gs_can.c
There was already provisions for this in the code. Tweaked CMake to
generate version.h automatically every build.
This is my proposal for #29 , adding build/version info to USB descriptors.
and under linux, the version string can be seen with lsusb -v  :
```
iProduct                2 cannette gs_usb
iSerial                 3 003300264250431420363230
bNumConfigurations      1
Configuration Descriptor:
bLength                 9
bDescriptorType         2
wTotalLength       0x0032
bNumInterfaces          2
bConfigurationValue     1
iConfiguration          4 fw_138e6cb_2021-02-17+
bmAttributes         0x80
(Bus Powered)
```
> Add git version string to USB config descriptor

- README.md
This patch adds a link to a manufacturer of the candleLight, where you can buy the adapter.
> README: add link to Linux Automation candleLight

- include/gs_usb.h
This PR documents the switchable termination support which will be added to the Linux driver soon. For the current Linux driver patch see: https://lore.kernel.org/all/20220918211802.692405-1-mkl@pengutronix.de/
This PR fixes issue https://github.com/candle-usb/candleLight_fw/issues/92
A reference implementation for switchable termination is added to the candleLight firmware in PR https://github.com/candle-usb/candleLight_fw/pull/108.
> gs_usb: document switchable termination support

- include/config.h
- src/gpio.c
Move the nCANSTBY_Pin to be avaliable for other boards. Make the
LED Rx and Tx pins optional.
Signed-off-by: Daniel Trevitz <daniel.trevitz@wika.com>
> Generalize the gpio configuration

- .github/workflows/pr.yml
Check the code formatting of a PR by looking up the files in git diff HEAD^
If the uncrustify config sees a change, yell about it.
The existing examples to uncrustify did not seem to work, so I forked and got it working.
In addition, this adds a directory filter, so we can safely ignore anything except the project's source and headers.
> Check code formatting on PR

- .gitignore
- CMakeLists.txt
- include/config.h
- include/usbd_gs_can.h
Take the first non STM32G0 specific patches from https://github.com/candle-usb/candleLight_fw/pull/126 and clean them up.
> Prepare for stm32g0

- CMakeLists.txt
First clean up the cmake file a bit, then add the `--print-memory-usage` linker option to print a overview of the memory usage.
> Cmake cleanups

- .editorconfig
GH parses the `.editorconfig` for displaying code. Add minimal editorconfig to display our code, the STM code looks good at first glance, too.
> editorconfig: add minimal editorconfig

- src/usbd_gs_can.c
The kernel reports error message as below,
Couldn't send data format (err=-32)
Seems caused by issue introduce in commit below,
a0caf93e50edd081
> Fix the issue that device cannot be recognized correctly

- include/led.h
- src/led.c
Sidequest from #143 - we're spending way too much time updating LEDs.
The most gain here is obtained from calling led_update() less often (every 10ms with this patch).
The commit changing the implementation of `led_indicate_trx()` showed surprisingly marginal gains - about 0.5% with a `cangen -L0 -g0 -p10 can0` benchmark.
can busload goes from ~ 12900 to 13120 frames/s with this PR.
> LED performance rework

- src/startup.c
atexit() is meaningless on this kind of embedded fw. Overriding this symbol saves a bunch of memory (384 B flash on cannette).
Ref:
https://sourceware.org/git/?p=newlib-cygwin.git;a=blob_plain;f=newlib/libc/stdlib/__atexit.c;hb=HEAD
> override __register_exitproc()

- ldscripts/ldscript_base.inc
startup files generated by stm32cubeIDE do this. Mostly useless since none of our code uses that, but I haven't found a more-official reference on whether or not those sections can be in read-only memory.
> ldscripts : move init/fini_array sections to flash

- libs/STM32_HAL/include/stm32g0xx/stm32g0xx_ll_usb.h
Under high CAN-TX load the endpoint on the stm32g0b will stall, this PR fixes the issue.
> Fix stm32g0b USB stall

- CMakeLists.txt
- README.md
- include/config.h
- DSD TECH SH-C30A: https://www.deshide.com/product-details.html?pid=384242&_t=1671089557
- FYSETC UCAN: https://www.fysetc.com/products/fysetc-ucan-board-based-on-stm32f072-usb-to-can-adapter-support-with-canable-candlelight-klipper-firmware
> Add support for additional F072 boards

- .github/workflows/ci.yml
Fixes #122
Before:
test run:
https://github.com/gemesa/candleLight_fw/actions/runs/4801634233/jobs/8544109203
where test code is:
```
- name: Get current date
id: date
run: echo "::set-output name=date::$(date +'%Y%m%d')"
- name: generate short hash
id: vars
run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
- name: print outputs
run: |
echo "${{steps.date.outputs.date}}"
echo "${{steps.vars.outputs.sha_short}}"
```
After:
test run:
https://github.com/gemesa/candleLight_fw/actions/runs/4801616342/jobs/8544066244
where test code is:
```
- name: Get current date
id: date
run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
- name: generate short hash
id: vars
run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
- name: print outputs
run: |
echo …
```
> CI: replace set-output

- include/compiler.h
- include/config.h
- include/list.h
- include/usbd_gs_can.h
- include/util.h
- include/util_internal.h
- uncrustify.cfg
Upgrade uncrustify's config file to the latest version.
Then uncrustify the header files in `include`.
Also I've found some unused defines in the `config.h`, remove them.
Remove comments about not connected silent pin and define `CONFIG_CANFD` to `1`, this way uncrustify produces a nice looking `config.h`.
> uncrustify: update config file and run uncrustify

- include/compiler.h
- include/config.h
- include/list.h
- include/usbd_gs_can.h
- include/util.h
- include/util_internal.h
- src/main.c
- uncrustify.cfg
This increases the size of the binary in a stm32f072 a bit:
before:
```
Memory region         Used Size  Region Size  %age Used
FLASH:       17296 B       128 KB     13.20%
RAM:        4268 B        16 KB     26.05%
```
after:
```
Memory region         Used Size  Region Size  %age Used
FLASH:       17312 B       128 KB     13.21%
RAM:        4268 B        16 KB     26.05%
```
Closes: https://github.com/candle-usb/candleLight_fw/issues/164
> main: provide weak symbols for _close, _lseek, _read, _write
